/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: kreems (https://sketchfab.com/kreems)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macintosh-128k-896ea439b67b4606a23fb8b93be6af6d
Title: Macintosh 128K
*/

import {
  PerspectiveCamera,
  RenderTexture,
  Text,
  useGLTF,
} from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useRef } from "react";
import * as THREE from "three";

const Computer = (props) => {
  const { nodes, materials } = useGLTF("/models/macintosh_128k.glb");

  const textRef = useRef();

  useFrame(
    (state) =>
      (textRef.current.position.x =
        -1 + Math.sin(state.clock.elapsedTime / 2) * 6.8),
  );

  return (
    <group
      {...props}
      dispose={null}
      position={[0, -2.85, 0]}
      rotation={[0, THREE.MathUtils.degToRad(-90), 0]}
    >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.007}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube008_hello_4_0.geometry}
              material={materials.hello_4}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Cube008_Macintosh-128K-retro_0"].geometry}
              material={materials["Macintosh-128K-retro"]}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube005_Material009_0.geometry}
              material={materials["Material.009"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube005_Material011_0.geometry}
              material={materials["Material.011"]}
            />
          </group>
          {/* mouse */}
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Plane001_Apple-0_0"].geometry}
              material={materials["Apple-0"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder007_grey_0.geometry}
              material={materials.grey}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Plane_Apple-0_0"].geometry}
              material={materials["Apple-0"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Cube001_Apple-0_0"].geometry}
              material={materials["Apple-0"]}
            />
          </group>
          {/* keyboard */}
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.korpus2_klava_2_1_0.geometry}
              material={materials.klava_2_1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.korpus2_Material005_0.geometry}
              material={materials["Material.005"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.knopki001_klava_2_0.geometry}
              material={materials.klava_2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder002_hello_4_0.geometry}
              material={materials.hello_4}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Sphere002_Material003_0.geometry}
              material={materials["Material.003"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder003_hello_4_0.geometry}
              material={materials.hello_4}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Sphere003_Material003_0.geometry}
              material={materials["Material.003"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube012_Material010_0.geometry}
              material={materials["Material.010"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube010_klava_2_1_0.geometry}
              material={materials.klava_2_1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube011_klava_2_1_0.geometry}
              material={materials.klava_2_1}
            />
          </group>
          {/* screen */}
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002_hello_0.geometry}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <meshBasicMaterial toneMapped={false}>
              <RenderTexture width={512} height={512} attach="map">
                <PerspectiveCamera
                  makeDefault
                  manual
                  aspect={1 / 1.2}
                  position={[0, 0, 25]}
                />
                <color attach="background" args={["#35c19f"]} />
                <ambientLight intensity={3} />
                <directionalLight position={[0, 0, 20]} />
                <Text
                  ref={textRef}
                  font="/fonts/RobotoMono-Bold.ttf"
                  position={[4.5, 7, 0]}
                  fontSize={4}
                  letterSpacing={-0.05}
                  color="black"
                >
                  welcome!
                </Text>
              </RenderTexture>
            </meshBasicMaterial>
          </mesh>

          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube003_hello_4_0.geometry}
            material={materials.hello_4}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_hello_4_0.geometry}
            material={materials.hello_4}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_hello_4_0.geometry}
            material={materials.hello_4}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube000_hello_4_0.geometry}
            material={materials.hello_4}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane003_hello_4_0.geometry}
            material={materials.hello_4}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plane004_Macintosh-128K-retro_0"].geometry}
            material={materials["Macintosh-128K-retro"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plane005_Macintosh-128K-retro_0"].geometry}
            material={materials["Macintosh-128K-retro"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane007_black_0.geometry}
            material={materials.black}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane006_black_0.geometry}
            material={materials.black}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plane009_Macintosh-128K-retro_0"].geometry}
            material={materials["Macintosh-128K-retro"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plane011_Macintosh-128K-retro_0"].geometry}
            material={materials["Macintosh-128K-retro"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plane010_Macintosh-128K-retro_0"].geometry}
            material={materials["Macintosh-128K-retro"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plane012_Macintosh-128K-retro_0"].geometry}
            material={materials["Macintosh-128K-retro"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plane013_Macintosh-128K-retro_0"].geometry}
            material={materials["Macintosh-128K-retro"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plane014_Macintosh-128K-retro_0"].geometry}
            material={materials["Macintosh-128K-retro"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plane015_Macintosh-128K-retro_0"].geometry}
            material={materials["Macintosh-128K-retro"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plane016_Macintosh-128K-retro_0"].geometry}
            material={materials["Macintosh-128K-retro"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plane017_Macintosh-128K-retro_0"].geometry}
            material={materials["Macintosh-128K-retro"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plane018_Macintosh-128K-retro_0"].geometry}
            material={materials["Macintosh-128K-retro"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plane019_Macintosh-128K-retro_0"].geometry}
            material={materials["Macintosh-128K-retro"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube009_hello_4_0.geometry}
            material={materials.hello_4}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube006_Macintosh_2_0.geometry}
            material={materials.Macintosh_2}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle001_grey_0.geometry}
            material={materials.grey}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/macintosh_128k.glb");

export default Computer;
