/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: kreems (https://sketchfab.com/kreems)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macintosh-128k-896ea439b67b4606a23fb8b93be6af6d
Title: Macintosh 128K
*/

import {
  PerspectiveCamera,
  RenderTexture,
  Text,
  useGLTF,
} from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useRef } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube002_hello_0: THREE.Mesh;
    Cube003_hello_4_0: THREE.Mesh;
    Cylinder_hello_4_0: THREE.Mesh;
    Cylinder001_hello_4_0: THREE.Mesh;
    Sphere_Material003_0: THREE.Mesh;
    Sphere001_Material003_0: THREE.Mesh;
    Cube007_Material002_0: THREE.Mesh;
    Cube008_hello_4_0: THREE.Mesh;
    ["Cube008_Macintosh-128K-retro_0"]: THREE.Mesh;
    Cube000_hello_4_0: THREE.Mesh;
    Plane003_hello_4_0: THREE.Mesh;
    ["Plane004_Macintosh-128K-retro_0"]: THREE.Mesh;
    ["Plane005_Macintosh-128K-retro_0"]: THREE.Mesh;
    Plane007_black_0: THREE.Mesh;
    Plane006_black_0: THREE.Mesh;
    Plane008_hello_4_0: THREE.Mesh;
    ["Plane008_Macintosh-128K-retro_0"]: THREE.Mesh;
    ["Plane009_Macintosh-128K-retro_0"]: THREE.Mesh;
    ["Plane011_Macintosh-128K-retro_0"]: THREE.Mesh;
    ["Plane010_Macintosh-128K-retro_0"]: THREE.Mesh;
    ["Plane012_Macintosh-128K-retro_0"]: THREE.Mesh;
    ["Plane013_Macintosh-128K-retro_0"]: THREE.Mesh;
    ["Plane014_Macintosh-128K-retro_0"]: THREE.Mesh;
    ["Plane015_Macintosh-128K-retro_0"]: THREE.Mesh;
    ["Plane016_Macintosh-128K-retro_0"]: THREE.Mesh;
    ["Plane017_Macintosh-128K-retro_0"]: THREE.Mesh;
    ["Plane018_Macintosh-128K-retro_0"]: THREE.Mesh;
    ["Plane019_Macintosh-128K-retro_0"]: THREE.Mesh;
    Cube009_hello_4_0: THREE.Mesh;
    Cube006_Macintosh_2_0: THREE.Mesh;
    Plane002_black_0: THREE.Mesh;
    Cylinder005_black_0: THREE.Mesh;
    BezierCurve001_grey_0: THREE.Mesh;
    Cube005_Material009_0: THREE.Mesh;
    Cube005_Material011_0: THREE.Mesh;
    Cylinder004_grey_0: THREE.Mesh;
    ["Plane001_Apple-0_0"]: THREE.Mesh;
    Cylinder007_grey_0: THREE.Mesh;
    ["Plane_Apple-0_0"]: THREE.Mesh;
    ["Cube001_Apple-0_0"]: THREE.Mesh;
    Cylinder010_black_0: THREE.Mesh;
    BezierCurve_black_0: THREE.Mesh;
    Cube_katushka_0: THREE.Mesh;
    Cube015_wood_0: THREE.Mesh;
    Cylinder006_grey_0: THREE.Mesh;
    Cylinder008_grey_0: THREE.Mesh;
    Cylinder009_grey_0: THREE.Mesh;
    Torus001_black_0: THREE.Mesh;
    Torus_black_0: THREE.Mesh;
    Cylinder011_black_0: THREE.Mesh;
    Cylinder014_black_0: THREE.Mesh;
    Cylinder013_black_0: THREE.Mesh;
    Cylinder012_black_0: THREE.Mesh;
    Plane025_decal_2_0: THREE.Mesh;
    Plane026_decal_3_0: THREE.Mesh;
    korpus2_klava_2_1_0: THREE.Mesh;
    korpus2_Material005_0: THREE.Mesh;
    knopki001_klava_2_0: THREE.Mesh;
    Cylinder002_hello_4_0: THREE.Mesh;
    Sphere002_Material003_0: THREE.Mesh;
    Cylinder003_hello_4_0: THREE.Mesh;
    Sphere003_Material003_0: THREE.Mesh;
    Cube012_Material010_0: THREE.Mesh;
    Cube010_klava_2_1_0: THREE.Mesh;
    Cube011_klava_2_1_0: THREE.Mesh;
    Circle001_grey_0: THREE.Mesh;
    Cube014_black_0: THREE.Mesh;
    Cube013_Material010_0: THREE.Mesh;
    Plane020_mahagon_3_0: THREE.Mesh;
    Plane027_ruchki_0: THREE.Mesh;
    Cylinder016_derevo_0: THREE.Mesh;
    Cylinder016_grifel004_0: THREE.Mesh;
    Cylinder016_cvet004_0: THREE.Mesh;
    Cylinder017_derevo_0: THREE.Mesh;
    Cylinder017_grifel_0: THREE.Mesh;
    Cylinder017_cvet_0: THREE.Mesh;
    Cylinder018_derevo_0: THREE.Mesh;
    Cylinder018_grifel001_0: THREE.Mesh;
    Cylinder018_cvet001_0: THREE.Mesh;
    Cylinder019_derevo_0: THREE.Mesh;
    Cylinder019_grifel002_0: THREE.Mesh;
    Cylinder019_cvet002_0: THREE.Mesh;
    Plane021_apple_2_0: THREE.Mesh;
    Cylinder020_derevo_0: THREE.Mesh;
    Cylinder020_grifel005_0: THREE.Mesh;
    Cylinder020_cvet003_0: THREE.Mesh;
    Cube004_oblogka_0: THREE.Mesh;
    Cube016_stranica_0: THREE.Mesh;
    Plane022_stiv_3_0: THREE.Mesh;
    Plane022_Material021_0: THREE.Mesh;
    Plane023_stiv_2_0: THREE.Mesh;
    Plane023_Material021_0: THREE.Mesh;
    Cylinder015_grey_0: THREE.Mesh;
    Torus002_black_0: THREE.Mesh;
    Torus003_black_0: THREE.Mesh;
    Plane024_knigi_0: THREE.Mesh;
    Cube017_oblogka_0: THREE.Mesh;
    Cube018_stranica_0: THREE.Mesh;
    stul_stul_0: THREE.Mesh;
    pol_kover_0: THREE.Mesh;
    pol_Material016_0: THREE.Mesh;
  };
  materials: {
    hello: THREE.MeshStandardMaterial;
    hello_4: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Macintosh-128K-retro"]: THREE.MeshStandardMaterial;
    black: THREE.MeshStandardMaterial;
    Macintosh_2: THREE.MeshStandardMaterial;
    grey: THREE.MeshStandardMaterial;
    ["Material.009"]: THREE.MeshStandardMaterial;
    ["Material.011"]: THREE.MeshStandardMaterial;
    ["Apple-0"]: THREE.MeshStandardMaterial;
    katushka: THREE.MeshStandardMaterial;
    wood: THREE.MeshStandardMaterial;
    decal_2: THREE.MeshStandardMaterial;
    decal_3: THREE.MeshStandardMaterial;
    klava_2_1: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    klava_2: THREE.MeshStandardMaterial;
    ["Material.010"]: THREE.MeshStandardMaterial;
    mahagon_3: THREE.MeshStandardMaterial;
    ruchki: THREE.MeshStandardMaterial;
    derevo: THREE.MeshStandardMaterial;
    ["grifel.004"]: THREE.MeshStandardMaterial;
    ["cvet.004"]: THREE.MeshStandardMaterial;
    grifel: THREE.MeshStandardMaterial;
    cvet: THREE.MeshStandardMaterial;
    ["grifel.001"]: THREE.MeshStandardMaterial;
    ["cvet.001"]: THREE.MeshStandardMaterial;
    ["grifel.002"]: THREE.MeshStandardMaterial;
    ["cvet.002"]: THREE.MeshStandardMaterial;
    apple_2: THREE.MeshStandardMaterial;
    ["grifel.005"]: THREE.MeshStandardMaterial;
    ["cvet.003"]: THREE.MeshStandardMaterial;
    oblogka: THREE.MeshStandardMaterial;
    stranica: THREE.MeshStandardMaterial;
    stiv_3: THREE.MeshStandardMaterial;
    ["Material.021"]: THREE.MeshStandardMaterial;
    stiv_2: THREE.MeshStandardMaterial;
    knigi: THREE.MeshStandardMaterial;
    stul: THREE.MeshPhysicalMaterial;
    kover: THREE.MeshStandardMaterial;
    ["Material.016"]: THREE.MeshStandardMaterial;
  };
};

const Computer = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF(
    "/models/macintosh_128k.glb",
  ) as GLTFResult;

  const textRef = useRef<any>();

  useFrame(
    (state) =>
      (textRef.current.position.x =
        -1 + Math.sin(state.clock.elapsedTime / 2) * 6.8),
  );

  return (
    <group
      {...props}
      dispose={null}
      position={[0, -2.85, 0]}
      rotation={[0, THREE.MathUtils.degToRad(-90), 0]}
    >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.007}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube008_hello_4_0.geometry}
              material={materials.hello_4}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Cube008_Macintosh-128K-retro_0"].geometry}
              material={materials["Macintosh-128K-retro"]}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube005_Material009_0.geometry}
              material={materials["Material.009"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube005_Material011_0.geometry}
              material={materials["Material.011"]}
            />
          </group>
          {/* mouse */}
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Plane001_Apple-0_0"].geometry}
              material={materials["Apple-0"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder007_grey_0.geometry}
              material={materials.grey}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Plane_Apple-0_0"].geometry}
              material={materials["Apple-0"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Cube001_Apple-0_0"].geometry}
              material={materials["Apple-0"]}
            />
          </group>
          {/* keyboard */}
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.korpus2_klava_2_1_0.geometry}
              material={materials.klava_2_1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.korpus2_Material005_0.geometry}
              material={materials["Material.005"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.knopki001_klava_2_0.geometry}
              material={materials.klava_2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder002_hello_4_0.geometry}
              material={materials.hello_4}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Sphere002_Material003_0.geometry}
              material={materials["Material.003"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder003_hello_4_0.geometry}
              material={materials.hello_4}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Sphere003_Material003_0.geometry}
              material={materials["Material.003"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube012_Material010_0.geometry}
              material={materials["Material.010"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube010_klava_2_1_0.geometry}
              material={materials.klava_2_1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube011_klava_2_1_0.geometry}
              material={materials.klava_2_1}
            />
          </group>
          {/* screen */}
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002_hello_0.geometry}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <meshBasicMaterial toneMapped={false}>
              <RenderTexture width={512} height={512} attach="map">
                <PerspectiveCamera
                  makeDefault
                  manual
                  aspect={1 / 1.2}
                  position={[0, 0, 25]}
                />
                <color attach="background" args={["#35c19f"]} />
                <ambientLight intensity={3} />
                <directionalLight position={[0, 0, 20]} />
                <Text
                  ref={textRef}
                  font="/fonts/RobotoMono-Bold.ttf"
                  position={[4.5, 7, 0]}
                  fontSize={4}
                  letterSpacing={-0.05}
                  color="black"
                >
                  welcome!
                </Text>
              </RenderTexture>
            </meshBasicMaterial>
          </mesh>

          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube003_hello_4_0.geometry}
            material={materials.hello_4}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_hello_4_0.geometry}
            material={materials.hello_4}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_hello_4_0.geometry}
            material={materials.hello_4}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube000_hello_4_0.geometry}
            material={materials.hello_4}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane003_hello_4_0.geometry}
            material={materials.hello_4}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plane004_Macintosh-128K-retro_0"].geometry}
            material={materials["Macintosh-128K-retro"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plane005_Macintosh-128K-retro_0"].geometry}
            material={materials["Macintosh-128K-retro"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane007_black_0.geometry}
            material={materials.black}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane006_black_0.geometry}
            material={materials.black}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plane009_Macintosh-128K-retro_0"].geometry}
            material={materials["Macintosh-128K-retro"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plane011_Macintosh-128K-retro_0"].geometry}
            material={materials["Macintosh-128K-retro"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plane010_Macintosh-128K-retro_0"].geometry}
            material={materials["Macintosh-128K-retro"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plane012_Macintosh-128K-retro_0"].geometry}
            material={materials["Macintosh-128K-retro"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plane013_Macintosh-128K-retro_0"].geometry}
            material={materials["Macintosh-128K-retro"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plane014_Macintosh-128K-retro_0"].geometry}
            material={materials["Macintosh-128K-retro"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plane015_Macintosh-128K-retro_0"].geometry}
            material={materials["Macintosh-128K-retro"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plane016_Macintosh-128K-retro_0"].geometry}
            material={materials["Macintosh-128K-retro"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plane017_Macintosh-128K-retro_0"].geometry}
            material={materials["Macintosh-128K-retro"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plane018_Macintosh-128K-retro_0"].geometry}
            material={materials["Macintosh-128K-retro"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plane019_Macintosh-128K-retro_0"].geometry}
            material={materials["Macintosh-128K-retro"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube009_hello_4_0.geometry}
            material={materials.hello_4}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube006_Macintosh_2_0.geometry}
            material={materials.Macintosh_2}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle001_grey_0.geometry}
            material={materials.grey}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/macintosh_128k.glb");

export default Computer;
